name: Deploy to Production ADF

on:
  push:
    branches:
      - main  # Change this to your main branch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: adf_publish

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az --version
        env: 
          AZURE_CONFIG_DIR:  ${{ runner.workspace }}/.azure
          FACTORY_NAME: ${{ secrets.FACTORY_NAME }}
          BASE_URL: ${{ secrets.BASE_URL }}
          CONNECTION_STRING_SECRET_NAME: ${{ secrets.CONNECTION_STRING_SECRET_NAME }}
          
      - name: Create Azure CLI config directory
        run: mkdir -p ${{ runner.workspace }}/.azure
        
      - name: Login to Azure
        run: az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }}
         
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CONFIG_DIR:  ${{ runner.workspace }}/.azure

      - name: Debug Deployment
        run: az deployment group validate --resource-group Yash-Prod --template-file ${{ runner.workspace }}/Data/adf-uat-ga/ARMTemplateForFactory.json

      - name: Deploy ARM Template to Production
        run: |
          az deployment group create \
            --resource-group Yash-Prod \
            --template-file ${{ runner.workspace }}/Data/adf-uat-ga/ARMTemplateForFactory.json \
            --parameters "factoryName=${FACTORY_NAME}" "ls_kv_uat_properties_typeProperties_baseUrl=${BASE_URL}" "ls_sto_uat_properties_typeProperties_connectionString_secretName=${CONNECTION_STRING_SECRET_NAME}" \
            --mode Incremental \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CONFIG_DIR:  ${{ runner.workspace }}/.azure
