name: Deploy to Production ADF


on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: adf_publish

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az --version
        env: 
          AZURE_CONFIG_DIR:  ${{ runner.workspace }}/.azure
          
      - name: Create Azure CLI config directory
        run: mkdir -p ${{ runner.workspace }}/.azure
        
      - name: List files
        run: ls -R

      - name: Print Directory
        run: pwd
        
      - name: Login to Azure
        run: az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }}
         
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CONFIG_DIR:  ${{ runner.workspace }}/.azure

      - name: Update Azure CLI
        run: az upgrade --yes --debug

      - name: Print Azure CLI Configuration
        run: cat ${{ runner.workspace }}/.azure

      - name: Print Parameters
        run: |
         echo "factoryName=${{ secrets.FACTORY_NAME }}"
         echo "ls_kv_uat_properties_typeProperties_baseUrl=${{ secrets.BASE_URL }}"
         echo "ls_sto_uat_properties_typeProperties_connectionString_secretName=${{ secrets.CONNECTION_STRING_SECRET_NAME }}"
      - name: Deploy ARM Template to Production
        run: |
          az deployment group create \
            --resource-group Yash-Prod \
            --template-file ${{ runner.workspace }}/Data/adf-uat-ga/ARMTemplateForFactory.json \
            --parameters factoryName="${{ secrets.FACTORY_NAME }}" ls_kv_uat_properties_typeProperties_baseUrl="${{ secrets.BASE_URL }}" ls_sto_uat_properties_typeProperties_connectionString_secretName="${{ secrets.CONNECTION_STRING_SECRET_NAME }}" \
            --mode Incremental \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            2>&1 | tee deployment_output.txt
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CONFIG_DIR:  ${{ runner.workspace }}/.azure
